# -*- coding: utf-8 -*-
"""RS No-Show.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wN9Ca27X3HvJglJzAqJYLcw4bs6EH6p5
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import time
import joblib

from google.colab import drive

# =========================================================
# BATCH 1 : PRA PEMROSESAN DATA
# =========================================================

# mengambil fil csv dari google drive
drive.mount('/content/drive',force_remount=True)
file_path = '/content/drive/My Drive/Colab Notebooks/data_pasien.xlsx'

# =========================================================
# 1. LOAD DATA
# =========================================================
# Ganti path sesuai lokasi file dataset
df = pd.read_excel(file_path,sheet_name='Sheet1')

print("=== RINGKASAN AWAL DATASET ===")
print(f"Jumlah baris awal : {len(df)}")
print(f"Jumlah kolom      : {df.shape[1]}")
print(df.dtypes)
# print(df.head())

jumlah_awal = len(df)

# Pastikan kolom tgl_jadwal dalam format datetime dengan penanganan kesalahan
df['tgl_jadwal'] = pd.to_datetime(df['tgl_jadwal'], format='%Y-%m-%d', errors='coerce')

# 1.1 Menghitung jumlah poli berdasarkan poli
jumlah_poli = df['poli'].nunique()
print(f'Jumlah pasien berdasarkan poli: {jumlah_poli}')
print()

# 1.2 Menghitung jumlah pasien berdasarkan no_rekam_medis
jumlah_pasien = df['no_rekam_medis'].nunique()
print(f'Jumlah pasien berdasarkan no_rekam_medis: {jumlah_pasien}')
print()

# 2. Menghitung jumlah pendaftaran berstatus TIDAK HADIR
tidak_hadir = df[df['status_kehadiran'] == 'TIDAK HADIR']
jumlah_tidak_hadir = tidak_hadir.shape[0]
persen_tidak_hadir = (jumlah_tidak_hadir / df.shape[0]) * 100
hadir = df[df['status_kehadiran'] == 'HADIR']
jumlah_hadir = hadir.shape[0]
persen_hadir = (jumlah_hadir / df.shape[0]) * 100
batal = df[df['status_kehadiran'] == 'BATAL']
jumlah_batal = batal.shape[0]
persen_batal = (jumlah_batal / df.shape[0]) * 100
print(f'Jumlah pendaftaran TIDAK HADIR: {jumlah_tidak_hadir} ({persen_tidak_hadir:.2f}%)')
print(f'Jumlah pendaftaran HADIR: {jumlah_hadir} ({persen_hadir:.2f}%)')
print(f'Jumlah pendaftaran BATAL: {jumlah_batal} ({persen_batal:.2f}%)')
print()

# 3. Menghitung no-show rate berdasarkan slot waktu
# Mengambil jam dari rentang waktu
def categorize_time(range_str):
    start_time, _ = range_str.split('-')
    return start_time

# Membuat salinan kolom untuk menghindari perubahan pada dataset asli
df_temp = df.copy()

# Ekstrak start_time sebagai kolom terpisah
df_temp['start_time'] = df_temp['jam_jadwal'].apply(categorize_time)

# Mengonversi start_time ke format datetime
df_temp['start_time'] = pd.to_datetime(df_temp['start_time'], format='%H:%M', errors='coerce').dt.time

# Menentukan kategori waktu berdasarkan start_time
df_temp['kategori_waktu'] = pd.cut(pd.to_datetime(df_temp['start_time'].astype(str)).dt.hour,
bins=[6, 12, 15, 19],
labels=['Pagi', 'Siang', 'Sore'],
right=False)

# Hitung total pendaftaran dan no-show per kategori waktu
total_per_waktu = df_temp.groupby('kategori_waktu').size()
no_show_per_waktu = df_temp[df_temp['status_kehadiran'] == 'TIDAK HADIR'].groupby('kategori_waktu').size()

# Hitung no-show rate
no_show_rate = (no_show_per_waktu / total_per_waktu) * 100

# Ambil nilai no-show rate untuk pagi, siang, dan sore
no_show_pagi = no_show_rate.get('Pagi', 0)
no_show_siang = no_show_rate.get('Siang', 0)
no_show_sore = no_show_rate.get('Sore', 0)

print(f'No-show rate pada slot Pagi: {no_show_pagi:.2f}%')
print(f'No-show rate pada slot Siang: {no_show_siang:.2f}%')
print(f'No-show rate pada slot Sore: {no_show_sore:.2f}%')

# 4. Menghitung no-show rate berdasarkan jenis pasien (LAMA/BARU)
# Hitung total pasien berdasarkan jenis dan no-show
total_pasien = df_temp.groupby('jenis_pasien').size()
no_show_pasien = tidak_hadir.groupby('jenis_pasien').size()

# Hitung no-show rate untuk pasien baru dan lama
no_show_rate_jenis = (no_show_pasien / total_pasien) * 100

# Ambil nilai no-show rate untuk pasien baru dan lama
no_show_baru = no_show_rate_jenis.get('BARU', 0)
no_show_lama = no_show_rate_jenis.get('LAMA', 0)

print(f'No-show rate untuk pasien Baru: {no_show_baru:.2f}%')
print(f'No-show rate untuk pasien Lama: {no_show_lama:.2f}%')
print()

# 5. Menghitung tren dari Januari ke Desember untuk pasien TIDAK HADIR
trennya = tidak_hadir.groupby(tidak_hadir['tgl_jadwal'].dt.month)['status_kehadiran'].count() / df_temp.groupby(df['tgl_jadwal'].dt.month)['status_kehadiran'].count() * 100

# Menyusun kembali indeks bulan ke dalam format yang lebih mudah dibaca
trennya.index = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

print('Tren persentase pendaftaran TIDAK HADIR dari Januari ke Desember:')
print(trennya)

# =========================================================
# 2. DATA CLEANING
# =========================================================

# --- 2.1 Konversi tipe data tanggal & jam ---
df['tgl_pendaftaran'] = pd.to_datetime(df['tgl_pendaftaran'], errors='coerce')
df['tgl_jadwal'] = pd.to_datetime(df['tgl_jadwal'], errors='coerce')

# --- 2.2 Cek & tangani missing value pada kolom kritikal ---
kolom_kritikal = ['tgl_jadwal', 'jam_jadwal', 'status_kehadiran']
print("\n=== JUMLAH MISSING VALUE PER KOLOM KRITIKAL ===")
print(df[kolom_kritikal].isnull().sum())

jumlah_sebelum_missing = len(df)
df = df.dropna(subset=kolom_kritikal)
jumlah_setelah_missing = len(df)
print(f"\nBaris dihapus karena missing value kritikal: {jumlah_sebelum_missing - jumlah_setelah_missing}")

# --- 2.3 Hapus duplikasi ---
jumlah_sebelum_dedup = len(df)
df = df.drop_duplicates(subset=['no_rekam_medis', 'tgl_jadwal', 'jam_jadwal'])
jumlah_setelah_dedup = len(df)
print(f"Baris dihapus karena duplikasi: {jumlah_sebelum_dedup - jumlah_setelah_dedup}")

# --- 2.4 Validasi konsistensi tanggal (tgl_pendaftaran harus <= tgl_jadwal) ---
jumlah_sebelum_validasi = len(df)
df = df[df['tgl_pendaftaran'] <= df['tgl_jadwal']]
jumlah_setelah_validasi = len(df)
print(f"Baris dihapus karena tgl_pendaftaran > tgl_jadwal: {jumlah_sebelum_validasi - jumlah_setelah_validasi}")

# --- 2.4b Validasi anomali usia ---
print(f"\nStatistik usia sebelum filter:\n{df['usia'].describe()}")

jumlah_sebelum_usia = len(df)
df = df[(df['usia'] >= 0) & (df['usia'] <= 120)]
jumlah_setelah_usia = len(df)
print(f"Baris dihapus karena usia anomali (<0 atau >120): {jumlah_sebelum_usia - jumlah_setelah_usia}")

# --- 2.4c Validasi anomali kategorik (jenis_pasien, jenis_kelamin, status_kehadiran) ---
kategori_valid = {
    'jenis_pasien': ['LAMA', 'BARU'],
    'jenis_kelamin': ['L', 'P'],
    'status_kehadiran': ['BATAL', 'HADIR', 'TIDAK HADIR']
}

for kolom, nilai_valid in kategori_valid.items():
    nilai_invalid = df.loc[~df[kolom].isin(nilai_valid), kolom].unique()
    if len(nilai_invalid) > 0:
        print(f"\nNilai tidak valid ditemukan pada '{kolom}': {nilai_invalid}")
    jumlah_sebelum = len(df)
    df = df[df[kolom].isin(nilai_valid)]
    jumlah_setelah = len(df)
    print(f"Baris dihapus karena '{kolom}' anomali: {jumlah_sebelum - jumlah_setelah}")

# --- 2.4d Validasi anomali no_rekam_medis kosong/tidak wajar ---
jumlah_sebelum_rm = len(df)
df = df[df['no_rekam_medis'].astype(str).str.strip() != '']
jumlah_setelah_rm = len(df)
print(f"Baris dihapus karena no_rekam_medis kosong: {jumlah_sebelum_rm - jumlah_setelah_rm}")

# --- 2.4e Validasi anomali poli kosong ---
jumlah_sebelum_poli = len(df)
df = df[df['poli'].astype(str).str.strip() != '']
jumlah_setelah_poli = len(df)
print(f"Baris dihapus karena poli kosong: {jumlah_sebelum_poli - jumlah_setelah_poli}")

# --- 2.5 Definisi variabel target ---
print("\n=== DISTRIBUSI STATUS_KEHADIRAN SEBELUM FILTER BATAL ===")
print(df['status_kehadiran'].value_counts())

jumlah_sebelum_batal = len(df)
df = df[df['status_kehadiran'] != 'BATAL']  # keluarkan BATAL
jumlah_setelah_batal = len(df)
print(f"\nBaris dikeluarkan karena status BATAL: {jumlah_sebelum_batal - jumlah_setelah_batal}")

df['target'] = df['status_kehadiran'].map({'HADIR': 0, 'TIDAK HADIR': 1})

jumlah_akhir = len(df)

print("\n=== RINGKASAN HASIL CLEANING ===")
print(f"Jumlah data awal   : {jumlah_awal}")
print(f"Jumlah data akhir  : {jumlah_akhir}")
print(f"Total baris dibuang: {jumlah_awal - jumlah_akhir} "
      f"({(jumlah_awal - jumlah_akhir)/jumlah_awal*100:.2f}%)")

print("\n=== DISTRIBUSI VARIABEL TARGET (SETELAH CLEANING) ===")
print(df['target'].value_counts())
print(df['target'].value_counts(normalize=True) * 100)



# =========================================================
# 3. FEATURE ENGINEERING
# =========================================================

# --- 3.1 lead_time_hari ---
df['lead_time_hari'] = (df['tgl_jadwal'] - df['tgl_pendaftaran']).dt.days

# --- 3.2 jam (jam MULAI dari format rentang "HH:MM-HH:MM") ---
jam_mulai_str = df['jam_jadwal'].astype(str).str.split('-').str[0].str.strip()
df['jam'] = pd.to_datetime(jam_mulai_str, format='%H:%M', errors='coerce').dt.hour

# --- 3.3 hari_jadwal (0=Senin, 6=Minggu) ---
df['hari_jadwal'] = df['tgl_jadwal'].dt.dayofweek

# --- 3.4 bulan_jadwal ---
df['bulan_jadwal'] = df['tgl_jadwal'].dt.month

# --- 3.5 is_weekend ---
df['is_weekend'] = df['hari_jadwal'].isin([5, 6]).astype(int)

# Cek missing value hasil feature engineering (mis. jam gagal parse)
print("\n=== MISSING VALUE SETELAH FEATURE ENGINEERING ===")
print(df[['lead_time_hari', 'jam', 'hari_jadwal', 'bulan_jadwal', 'is_weekend']].isnull().sum())

# Hapus baris yang gagal feature engineering (jika ada)
jumlah_sebelum_fe = len(df)
df = df.dropna(subset=['lead_time_hari', 'jam', 'hari_jadwal', 'bulan_jadwal'])
jumlah_setelah_fe = len(df)
print(f"Baris dihapus karena gagal feature engineering: {jumlah_sebelum_fe - jumlah_setelah_fe}")

# --- 3.6 Cek nilai lead_time_hari negatif (anomali) ---
print(f"\nJumlah lead_time_hari negatif (anomali): {(df['lead_time_hari'] < 0).sum()}")
df = df[df['lead_time_hari'] >= 0]

# =========================================================
# 4. ENCODING VARIABEL KATEGORIK
# =========================================================

from sklearn.preprocessing import LabelEncoder

# # --- 4.1 poli_enc ---
le_poli = LabelEncoder()
df['poli_enc'] = le_poli.fit_transform(df['poli'])


# Cek missing value hasil encoding

print("\n=== MAPPING LABEL ENCODING POLI ===")
mapping_poli = dict(zip(le_poli.classes_, le_poli.transform(le_poli.classes_)))
# for k, v in mapping_poli.items():
#     print(f"{k} -> {v}")

# Membuat DataFrame dari dictionary
df_mapping = pd.DataFrame(
    mapping_poli.items(),
    columns=['poli', 'poli_enc']
)

# Simpan hasil encoding variabel kategorik poli
file_path = '/content/drive/My Drive/Colab Notebooks/Data/poli_enc.csv'
df_mapping.to_csv(file_path, index=False)
print("\nHasil encoding variabel kategorik poli disimpan sebagai 'poli_enc.csv'")

# --- 4.2 jenis_pasien_enc ---
df['jenis_pasien_enc'] = df['jenis_pasien'].map({'BARU': 1, 'LAMA': 0})

# # --- 4.3 gender_enc ---
df['gender_enc'] = df['jenis_kelamin'].map({'L': 1, 'P': 0})

# Cek missing value hasil encoding
print("\n=== MISSING VALUE SETELAH ENCODING ===")
print(df[['poli_enc', 'jenis_pasien_enc', 'gender_enc']].isnull().sum())



df = df.dropna(subset=['jenis_pasien_enc', 'gender_enc'])

# =========================================================
# 5. FINALISASI DATASET
# =========================================================

fitur_final = [
    'lead_time_hari', 'jam', 'hari_jadwal', 'bulan_jadwal',
    'is_weekend', 'poli_enc', 'jenis_pasien_enc', 'gender_enc', 'usia'
]

df_final = df[fitur_final + ['target', 'tgl_pendaftaran', 'tgl_jadwal']].copy()

print("\n=== RINGKASAN DATASET FINAL SIAP DIPAKAI ===")
print(f"Jumlah baris  : {len(df_final)}")
print(f"Jumlah fitur  : {len(fitur_final)}")
print(df_final[fitur_final].describe())

print("\n=== DISTRIBUSI TARGET FINAL ===")
print(df_final['target'].value_counts())
print(df_final['target'].value_counts(normalize=True) * 100)

# Simpan hasil preprocessing untuk dipakai di batch berikutnya
file_path = '/content/drive/My Drive/Colab Notebooks/Data/dataset_preprocessed.csv'
df_final.to_csv(file_path, index=False)
print("\nDataset hasil preprocessing disimpan sebagai 'dataset_preprocessed.csv'")

# =========================================================
# BATCH 2 : PEMBAGIAN DATA
# =========================================================

# =========================================================
# 1. LOAD DATASET HASIL PREPROCESSING
# =========================================================
file_path_preprocessed = '/content/drive/My Drive/Colab Notebooks/Data/dataset_preprocessed.csv'
df_preprocessed = pd.read_csv(file_path_preprocessed, parse_dates=['tgl_pendaftaran', 'tgl_jadwal'])

print(f"Jumlah data yang akan dibagi: {len(df)}")

# =========================================================
# 2. URUTKAN DATA SECARA KRONOLOGIS
# =========================================================
# Diurutkan berdasarkan tgl_jadwal, karena split kronologis dimaksudkan
# untuk mensimulasikan skenario nyata: model dilatih dari kunjungan masa lalu
# untuk memprediksi kunjungan yang akan datang.
df_preprocessed = df_preprocessed.sort_values('tgl_jadwal').reset_index(drop=True)

print(f"\nRentang tgl_jadwal keseluruhan data:")
print(f"Awal : {df_preprocessed['tgl_jadwal'].min()}")
print(f"Akhir: {df_preprocessed['tgl_jadwal'].max()}")

# =========================================================
# 3. CHRONOLOGICAL SPLIT 80:20
# =========================================================
split_index = int(len(df) * 0.8)

df_train = df_preprocessed.iloc[:split_index].copy()
df_test = df_preprocessed.iloc[split_index:].copy()

# =========================================================
# 4. RINGKASAN HASIL SPLIT
# =========================================================
print("\n=== RINGKASAN PEMBAGIAN DATA ===")
print(f"Jumlah data latih (train) : {len(df_train)} ({len(df_train)/len(df)*100:.2f}%)")
print(f"Jumlah data uji (test)    : {len(df_test)} ({len(df_test)/len(df)*100:.2f}%)")

print("\n=== RENTANG TANGGAL DATA LATIH ===")
print(f"Dari : {df_train['tgl_jadwal'].min()}")
print(f"Hingga: {df_train['tgl_jadwal'].max()}")

print("\n=== RENTANG TANGGAL DATA UJI ===")
print(f"Dari : {df_test['tgl_jadwal'].min()}")
print(f"Hingga: {df_test['tgl_jadwal'].max()}")

# =========================================================
# 5. DISTRIBUSI TARGET PADA MASING-MASING SUBSET
# =========================================================
print("\n=== DISTRIBUSI TARGET - DATA LATIH ===")
print(df_train['target'].value_counts())
print(df_train['target'].value_counts(normalize=True) * 100)

print("\n=== DISTRIBUSI TARGET - DATA UJI ===")
print(df_test['target'].value_counts())
print(df_test['target'].value_counts(normalize=True) * 100)

# =========================================================
# 6. SIMPAN HASIL SPLIT UNTUK BATCH BERIKUTNYA
# =========================================================
file_path_train = '/content/drive/My Drive/Colab Notebooks/Data/data_train.csv'
file_path_test = '/content/drive/My Drive/Colab Notebooks/Data/data_test.csv'

df_train.to_csv(file_path_train, index=False)
df_test.to_csv(file_path_test, index=False)

print("\nData latih disimpan sebagai 'data_train.csv'")
print("Data uji disimpan sebagai 'data_test.csv'")